name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  DATABASE_URL: "https://fake.com" # Define your environment variables here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Change this to the desired Node.js version

      - name: Set up environment variables
        run: echo "NODE_ENV=${NODE_ENV}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: TypeScript type checking
        run: npm run typecheck

      - name: Linting
        run: npm run lint
